-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua

---@module 'hl'

-- Media Bindings

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true })
hl.bind("SHIFT + XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 100%"), { locked = true })
hl.bind("SHIFT + XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 0%"), { locked = true })

hl.bind("XF86KbdBrightnessUp", hl.dsp.exec_cmd("brightnessctl -d*::kbd_backlight set +1"), { locked = true })
hl.bind("XF86KbdBrightnessDown", hl.dsp.exec_cmd("brightnessctl -d*::kbd_backlight set 1-"), { locked = true })
hl.bind("XF86KbdLightOnOff", hl.dsp.exec_cmd("brightnessctl -d*::kbd_backlight set toggle"), { locked = true })

hl.bind("ALT + XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+"), { locked = true })
hl.bind("ALT + XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"), { locked = true })
hl.bind("ALT + XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +1%"), { locked = true })
hl.bind("ALT + XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 1%-"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Clipboard Bindings

hl.bind("SUPER + C", hl.dsp.send_shortcut({ mods = "CTRL", key = "Insert", window = "activewindow" }))
hl.bind("SUPER + V", hl.dsp.send_shortcut({ mods = "SHIFT", key = "Insert", window = "activewindow" }))
hl.bind("SUPER + X", hl.dsp.send_shortcut({ mods = "CTRL", key = "X", window = "activewindow" }))

-- Tiling Bindings

hl.bind("SUPER + W", hl.dsp.window.close())
hl.bind("SUPER + J", hl.dsp.layout("togglesplit"))
hl.bind("SUPER + P", hl.dsp.window.pseudo()) -- dwindle
hl.bind("SUPER + T", hl.dsp.window.float())

hl.bind("SUPER + F", hl.dsp.window.fullscreen())
-- hl.bind("SUPER + CTRL + F", hl.dsp.window.fullscreen_state({ internal = 0, client = 2 }))
-- hl.bind("SUPER + ALT + F", hl.dsp.window.fullscreen())

hl.bind("SUPER + LEFT", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + RIGHT", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + UP", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + DOWN", hl.dsp.focus({ direction = "down" }))

hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind("SUPER + SHIFT + ALT + 1", hl.dsp.window.move({ workspace = 1 , follow = false}))
hl.bind("SUPER + SHIFT + ALT + 2", hl.dsp.window.move({ workspace = 2 , follow = false}))
hl.bind("SUPER + SHIFT + ALT + 3", hl.dsp.window.move({ workspace = 3 , follow = false}))
hl.bind("SUPER + SHIFT + ALT + 4", hl.dsp.window.move({ workspace = 4 , follow = false}))
hl.bind("SUPER + SHIFT + ALT + 5", hl.dsp.window.move({ workspace = 5 , follow = false}))
hl.bind("SUPER + SHIFT + ALT + 6", hl.dsp.window.move({ workspace = 6 , follow = false}))
hl.bind("SUPER + SHIFT + ALT + 7", hl.dsp.window.move({ workspace = 7 , follow = false}))
hl.bind("SUPER + SHIFT + ALT + 8", hl.dsp.window.move({ workspace = 8 , follow = false}))
hl.bind("SUPER + SHIFT + ALT + 9", hl.dsp.window.move({ workspace = 9 , follow = false}))
hl.bind("SUPER + SHIFT + ALT + 0", hl.dsp.window.move({ workspace = 10 , follow = false}))

hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("scratchpad"))
hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special:scratchpad" , follow = false}))

hl.bind("SUPER + TAB", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + SHIFT + TAB", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + CTRL + TAB", hl.dsp.focus({ workspace = "previous" }))

hl.bind("SUPER + SHIFT + ALT + LEFT", hl.dsp.workspace.move({ monitor = "l" }))
hl.bind("SUPER + SHIFT + ALT + RIGHT", hl.dsp.workspace.move({ monitor = "r" }))
hl.bind("SUPER + SHIFT + ALT + UP", hl.dsp.workspace.move({ monitor = "u" }))
hl.bind("SUPER + SHIFT + ALT + DOWN", hl.dsp.workspace.move({ monitor = "d" }))

hl.bind("SUPER + SHIFT + LEFT", hl.dsp.window.swap({ direction = "left" }))
hl.bind("SUPER + SHIFT + RIGHT", hl.dsp.window.swap({ direction = "right" }))
hl.bind("SUPER + SHIFT + UP", hl.dsp.window.swap({ direction = "up" }))
hl.bind("SUPER + SHIFT + DOWN", hl.dsp.window.swap({ direction = "down" }))

hl.bind("ALT + TAB", hl.dsp.window.cycle_next())
hl.bind("ALT + SHIFT + TAB", hl.dsp.window.cycle_next({ next = false }))

hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true }) -- NOT WRITTEN IN KEYBINDINGS

hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("SUPER + G", hl.dsp.group.toggle()) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + G", hl.dsp.window.move({ out_of_group = true })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + LEFT", hl.dsp.window.move({ into_group = "left" })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + RIGHT", hl.dsp.window.move({ into_group = "right" })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + UP", hl.dsp.window.move({ into_group = "up" })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + DOWN", hl.dsp.window.move({ into_group = "down" })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + TAB", hl.dsp.group.next()) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + SHIFT + TAB", hl.dsp.group.next({ forward = false })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + CTRL + LEFT", hl.dsp.group.next({ forward = false })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + CTRL + RIGHT", hl.dsp.group.next()) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + mouse_down", hl.dsp.group.next()) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + mouse_up", hl.dsp.group.next({ forward = false })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + 1", hl.dsp.group.next({ forward = false })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + 2", hl.dsp.group.next({ forward = false })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + 3", hl.dsp.group.next({ forward = false })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + 4", hl.dsp.group.next({ forward = false })) -- NOT WRITTEN IN KEYBINDINGS
hl.bind("SUPER + ALT + 5", hl.dsp.group.next({ forward = false })) -- NOT WRITTEN IN KEYBINDINGS

-- Utility Bindings

hl.bind("SUPER + ALT + SPACE", hl.dsp.exec_cmd("~/.config/waybar/scripts/main-menu.sh"))
hl.bind("SUPER + SPACE", hl.dsp.exec_cmd("fuzzel --show drun"))
hl.bind("SUPER + B", hl.dsp.exec_cmd("pkill swaybg || setsid -f swaybg -i ~/.config/hypr/background.png -m fill < /dev/null > /dev/null 2>&1"))
hl.bind("SUPER + R", hl.dsp.exec_cmd("~/.config/waybar/scripts/reminder.sh"))
hl.bind("SUPER + Q", hl.dsp.exec_cmd("ghostty"))
hl.bind("SUPER + CTRL + E", hl.dsp.exec_cmd("rofimoji --selector fuzzel --action print | tr -d '\n' | wl-copy"))
hl.bind("XF86PowerOff", hl.dsp.exec_cmd("~/.config/waybar/scripts/power-menu.sh"), { locked = true })

hl.bind("XF86Calculator", hl.dsp.exec_cmd("gnome-calculator"))

hl.bind("SUPER + SHIFT + SPACE", hl.dsp.exec_cmd("pkill waybar || waybar"))

hl.bind("SUPER + COMMA", hl.dsp.exec_cmd("makoctl dismiss"))
hl.bind("SUPER + SHIFT + COMMA", hl.dsp.exec_cmd("makoctl dismiss --all"))
hl.bind("SUPER + CTRL + COMMA", hl.dsp.exec_cmd("makoctl mode | grep -q \"do-not-disturb\" && makoctl mode -r \"do-not-disturb\" || makoctl mode -a \"do-not-disturb\""))
hl.bind("SUPER + ALT + COMMA", hl.dsp.exec_cmd("makoctl invoke"))
hl.bind("SUPER + SHIFT + ALT + COMMA", hl.dsp.exec_cmd("makoctl restore"))

hl.bind("PRINT", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy --type image/png && notify-send \"Screenshot\" \"Screenshot copied to clipboard\""))
hl.bind("SUPER + PRINT", hl.dsp.exec_cmd("pkill hyprpicker || hyprpicker -a"))
hl.bind("ALT + PRINT", hl.dsp.exec_cmd("~/.config/waybar/scripts/screenrecorder.sh"))

hl.bind("SUPER + L", hl.dsp.exec_cmd("hyprlock"))

-- Env

hl.env("XCURSOR_SIZE", 24)
hl.env("HYPRCURSOR_SIZE", 24)
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("MOZ_ENABLE_WAYLAND", 1)
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("OZONE_PLATFORM", "wayland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

-- Display

hl.env("GDK_SCALE", 2)

hl.monitor({
	output   = "",
	mode	 = "preferred",
	position = "auto",
	scale	= 1.4,
})

-- Input

hl.config({
	input = {
		kb_layout = "us",
		kb_options = "capslock:caps",
		repeat_rate = 40,
		repeat_delay = 600,
		numlock_by_default = true,
		sensitivity = 0.4,
		touchpad = {
			natural_scroll = true,
			clickfinger_behavior = true,
			scroll_factor = 0.4,
		},
	},
})

-- Terminal Scrolling

hl.window_rule({
	name  = "scroll_touchpad_1_5_204",
	match = {
		class = "(Alacritty|kitty|foot)",
	},
	scroll_touchpad = 1.5,
})

hl.window_rule({
	name  = "scroll_touchpad_0_2_205",
	match = {
		class = "com.mitchellh.ghostty",
	},
	scroll_touchpad = 0.2,
})

-- Enable touchpad gestures for changing workspaces

hl.gesture({
	["fingers"] = 3,
	["direction"] = "horizontal",
	["action"] = "workspace",
})

-- General Aesthetics

local activeBorderColor = "rgba(ffffffaa) rgba(ffffffaa) 45deg"

local inactiveBorderColor = "rgba(000000aa) rgba(000000aa) 45deg"

hl.config({
	general = {
		gaps_in = 0,
		gaps_out = 0,
		border_size = 2,
		resize_on_border = false,
		allow_tearing = false,
		layout = "dwindle",
		col = {
			active_border = { colors = { "rgba(ffffffaa)", "rgba(ffffffaa)" }, angle = 45 },
			inactive_border = { colors = { "rgba(000000aa)", "rgba(000000aa)" }, angle = 45 },
		},
	},
})

hl.config({
	decoration = {
		rounding = 0,
		shadow = {
			enabled = true,
			range = 2,
			render_power = 3,
			color = "rgba(1a1a1aee)",
		},
		blur = {
			enabled = false,
			size = 2,
			passes = 2,
			special = true,
			brightness = 0.60,
			contrast = 0.75,
		},
	},
})

hl.config({
	group = {
		groupbar = {
			font_size = 12,
			font_family = "monospace",
			font_weight_active = "ultraheavy",
			font_weight_inactive = "normal",
			indicator_height = 0,
			indicator_gap = 5,
			height = 22,
			gaps_in = 5,
			gaps_out = 0,
			text_color = "rgb(ffffff)",
			text_color_inactive = "rgba(ffffff90)",
			col = {
				active = "rgba(00000040)",
				inactive = "rgba(00000020)",
			},
			gradients = true,
			gradient_rounding = 0,
			gradient_round_only_edges = false
		},
		col = {
			border_active = { colors = { "rgba(0099ffaa)", "rgba(964b00aa)" }, angle = 45 },
			border_inactive = { colors = { "rgba(004d80aa)", "rgba(4b2600aa)" }, angle = 45 },
			border_locked_active = { colors = { "rgba(0099ffaa)", "rgba(964b00aa)" }, angle = 45 },
			border_locked_inactive = { colors = { "rgba(004d80aa)", "rgba(4b2600aa)" }, angle = 45 },
		}
	}
})

hl.config({
	animations = {
		enabled = true -- or false
	},
})
hl.curve("easeOutQuint", {
	type = "bezier",
	points = { { 0.23, 1 }, { 0.32, 1 } },
})
hl.curve("easeInOutCubic", {
	type = "bezier",
	points = { { 0.65, 0.05 }, { 0.36, 1 } },
})
hl.curve("linear", {
	type = "bezier",
	points = { { 0, 0 }, { 1, 1 } },
})
hl.curve("almostLinear", {
	type = "bezier",
	points = { { 0.5, 0.5 }, { 0.75, 1.0 } },
})
hl.curve("quick", {
	type = "bezier",
	points = { { 0.15, 0 }, { 0.1, 1 } },
})
hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 3.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = false, speed = 0, bezier = "ease" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3, bezier = "easeOutQuint", style = "slidevert" })

hl.config({
	dwindle = {
		preserve_split = true,
		force_split = 2,
	},
})

hl.config({
	scrolling = {
		column_width = 0.49,
	},
})

hl.config({
	master = {
		new_status = "master",
	},
})

hl.config({
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		disable_scale_notification = true,
		focus_on_activate = true,
		anr_missed_pings = 3,
		on_focus_under_fullscreen = 1,
	},
})

hl.config({
	cursor = {
		hide_on_key_press = true,
		warp_on_change_workspace = 1,
	},
})

hl.config({
	binds = {
		hide_special_on_workspace_change = true,
	},
})

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("mako")
	hl.exec_cmd("waybar")
	hl.exec_cmd("swaybg -i ~/.config/hypr/background.png -m fill")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
end)
